Output charmify.gif

Set Width 1600
Set Height 1040

Sleep 100ms

Type@500ms ./charmify
Sleep 5s
Enter

Sleep 5s

Hide
Down 1
Sleep 3s
Show

Sleep 5s

Hide
Type "t"
Sleep 2s
Show

Sleep 5s

Hide
Type "t"
Sleep 2s
Show

Sleep 5s

Hide
Type "c"
Show

Sleep 5s

Type@500ms "Give a talk"
Sleep 2s
Enter
Type@500ms "at GopherCon"
Sleep 2s
Enter
Type@500ms "1"
Sleep 2s
Enter

Sleep 5s

Hide
Down 1
Sleep 1s
Down 1
Show

Sleep 5s

Hide
Type "t"
Show

Sleep 5s

Hide
Type "q"
Show